#link container on quay with qiime2
container_image = docker://quay.io/qiime2/amplicon:2025.4

#reference your sh file
executable = 01_demux.sh

#state path to input and expected output files
transfer_input_files = \
  file:///staging/mmichaelis/input_outputs/00_pipeline_inputs/emp-single-end-sequences.tar.gz, \
  file:///staging/mmichaelis/input_outputs/00_pipeline_inputs/sample-metadata.tsv, \
  #make sure to reference your home directory
  file:///home/mmichaelis/16S_chtc/01_demux.sh

transfer_output_files = emp-single-end-sequences.qza, demux.qza, demux.qzv

#state path to where output files will go
transfer_output_remaps = \
  "emp-single-end-sequences.qza = file:///staging/mmichaelis/input_outputs/01_demux", \
  "demux.qza = file:///staging/mmichaelis/input_outputs/01_demux", \
  "demux.qzv = file:///staging/mmichaelis/input_outputs/01_demux"

#state path/name of log, err and out files
log = logs/01_demux$(cluster).log
error = logs/01_demux$(cluster).err
output = logs/01_demux$(cluster).out

requirements = (HasCHTCStaging == true) && (HasChtcProjects == true)

#make requests and queue
request_cpus = 8
request_memory = 16GB
request_disk = 14GB

queue
