#link container on quay with qiime2
container_image = docker://quay.io/qiime2/amplicon:2025.4

#reference your sh file
executable = 01_demux.sh

#state path to input and expected output files
transfer_input_files = \
  file:///staging/mmichaelis/qiime-amp-pipeline/emp-single-end-sequences.tar.gz, \
  file:///staging/mmichaelis/qiime-amp-pipeline/sample-metadata.tsv, \
  file:///staging/mmichaelis/qiime-amp-pipeline/01_demux.sh

transfer_output_files = emp-single-end-sequences.qza, demux.qza, demux.qzv

#state path/name of log, err and out files
log = logs/01_demux$(cluster).log
error = logs/01_demux$(cluster).err
output = logs/01_demux$(cluster).out

requirements = (HasCHTCStaging == true) && (HasChtcProjects == true)

#make requests and queue
request_cpus = 8
request_memory = 16GB
request_disk = 14GB

queue
