#link container 
container_image = docker://quay.io/qiime2/amplicon:2025.4

#reference your sh file
executable = 03_features.sh

#state path to input and expected output files
transfer_input_files = \
  file:///staging/mmichaelis/03_features/table.qza, \
  file:///staging/mmichaelis/03_features/rep-seqs.qza, \
  file:///staging/mmichaelis/03_features/sample-metadata.tsv

transfer_output_files = table.qzv, rep-seqs.qzv

#state path/name of log, err and out files
log = logs/03_features$(cluster).log
error = logs/03_features$(cluster).err
output = logs/03_features$(cluster).out

requirements = (HasCHTCStaging == true) && (HasChtcProjects == true)

#make requests and queue ###trying 12 for sizes this time
request_cpus = 8
request_memory = 12GB
request_disk = 12GB

queue
