#link container on quay with qiime2
container_image = docker://quay.io/qiime2/amplicon:2025.4

#reference your sh file
executable = 01_demux.sh
staging_path = file:///staging/mmichaelis/input_outputs

#state path to input and expected output files
transfer_input_files = \
  $(staging_path)/00_pipeline_inputs/emp-single-end-sequences.tar.gz, \
  $(staging_path)/00_pipeline_inputs/sample-metadata.tsv

transfer_output_files = emp-single-end-sequences.qza, demux.qza, demux.qzv

#state path to where output files will go
transfer_output_remaps = \
  "emp-single-end-sequences.qza = $(staging_path)/01_demux/emp-single-end-sequences.qza; \
  demux.qza = $(staging_path)/01_demux/demux.qza; \
  demux.qzv = $(staging_path)/01_demux/demux.qzv"

#state path/name of log, err and out files
log = logs/01_demux$(cluster).log
error = logs/01_demux$(cluster).err
output = logs/01_demux$(cluster).out

requirements = (HasCHTCStaging == true) && (HasChtcProjects == true)

#make requests and queue
request_cpus = 8
request_memory = 14GB
request_disk = 12GB

queue
