b# link container on quay with qiime2
container_image = docker://quay.io/qiime2/amplicon:2025.4

# reference your sh file
executable = 01_demux.sh
staging_path = file:///staging/mmichaelis/input_outputs

# input and executable files
transfer_input_files = \
  $(staging_path)/00_pipeline_inputs/emp-single-end-sequences.tar.gz, \
  $(staging_path)/00_pipeline_inputs/sample-metadata.tsv

# expected outputs
transfer_output_files = emp-single-end-sequences.qza, demux.qza, demux.qzv

# remap outputs to correct subfolder under staging
transfer_output_remaps = \
  "emp-single-end-sequences.qza = $(staging_path)/01_demux/emp-single-end-sequences.qza; \
  demux.qza = $(staging_path)/01_demux/demux.qza; \
  demux.qzv = $(staging_path)/01_demux/demux.qzv"

# log files
log = logs/01_demux$(cluster).log
error = logs/01_demux$(cluster).err
output = logs/01_demux$(cluster).out

# special CHTC requirements
requirements = (HasCHTCStaging == true) && (HasChtcProjects == true)

# resource requests
request_cpus = 8
request_memory = 12GB
request_disk = 12GB

queue
