# link container on quay with qiime2
container_image = docker://quay.io/qiime2/amplicon:2025.4

#reference sh script
executable = 01_import.sh
staging_path = file:///staging/$(netid)/input_outputs

#state path to input files
transfer_input_files = \
  $(staging_path)/00_pipeline_inputs/sample-metadata.tsv

#state the output files
transfer_output_files = demux.qza, demux.qzv

#remap outputs to desired location
transfer_output_remaps = \
  demux.qza = $(staging_path)/01_import-demux/demux.qza; \
  demux.qzv = $(staging_path)/01_import-demux/demux.qzv"

#create log/err/out files
log = logs/01_import$(cluster).log
error = logs/01_import$(cluster).err
output = logs/01_import$(cluster).out

#set requirements
requirements = (HasCHTCStaging == true) && (HasChtcProjects == true) && (OpSysMajorVer > 7)

#make requests and queue
request_cpus = 8
request_memory = 12GB
request_disk = 12GB

queue




