#link container 
container_image = docker://quay.io/qiime2/amplicon:2025.4

#reference your sh file
executable = 02_dada2_qc.sh
staging_path = file:///staging/mmichaelis/input_outputs

#state path to input and expected output files
transfer_input_files = \
  $(staging_path)/01_demux/demux.qza

transfer_output_files = rep-seqs.qza, table.qza, stats.qza, stats.qzv

#state path to where output files will go
transfer_output_remaps = \
  "rep-seqs.qza = $(staging_path)/02_dada2_qc/rep-seqs.qza; \
  table.qza = $(staging_path)/02_dada2_qc/table.qza; \
  stats.qza = $(staging_path)02_dada2_qc/stats.qza; \
  stats.qzv = $(staging_path)/02_dada2_qc/stats.qzv"

#state path/name of log, err and out files
log = logs/02_dada2_qc$(cluster).log
error = logs/02_dada2_qc$(cluster).err
output = logs/02_dada2_qc$(cluster).out

requirements = (HasCHTCStaging == true) && (HasChtcProjects == true)

#make requests and queue
request_cpus = 8
request_memory = 12GB
request_disk = 12GB

queue
