#link container
container_image = docker://quay.io/qiime2/amplicon:2025.4

#reference sh script
executable = 03_features.sh
staging_path = file:///staging/mmichaelis/input_outputs

#state path to input files
transfer_input_files = \
  $(staging_path)/02_dada2_qc/table.qza, \
  $(staging_path)/02_dada2_qc/rep-seqs.qza, \
  $(staging_path)/02_dada2_qc/sample-metadata.tsv

#state the output files
transfer_output_files = table.qzv, rep-seqs.qzv

#remap outputs to desired location
transfer_output_remaps = \
  "table.qzv = $(staging_path)/03_features/table.qzv; rep-seqs.qzv = $(staging_path)/03_features/rep-seqs.qzv"

#create log/err/out files
log = logs/03_features$(cluster).log
error = logs/03_features$(cluster).err
output = logs/03_features$(cluster).out

#set requirements
requirements = (HasCHTCStaging == true) && (HasChtcProjects == true) && (OpSysMajorVer > 7)

#make requests and queue
request_cpus = 8
request_memory = 14GB
request_disk = 13GB

queue
