#link container 
container_image = docker://quay.io/qiime2/amplicon:2025.4

#reference sh script
executable = 04_phytree.sh
staging_path = file:///staging/$(netid)/input_outputs

#state path to input files
transfer_input_files = \
  $(staging_path)/02_dada2_qc/rep-seqs.qza

#state the output files
transfer_output_files = aligned-rep-seqs.qza, masked-aligned-rep-seqs.qza, \
			unrooted-tree.qza, rooted-tree.qza

#remap outputs to desired location
transfer_output_remaps = "aligned-rep-seqs.qza = $(staging_path)/04_phytree/aligned-rep-seqs.qza; masked-aligned-rep-seqs.qza = $(staging_path)/04_phytree/masked-aligned-rep-seqs.qza; unrooted-tree.qza = $(staging_path)/04_phytree/unrooted-tree.qza; rooted-tree.qza = $(staging_path)/04_phytree/rooted-tree.qza"

#create log/err/out files
log = logs/04_features$(cluster).log
error = logs/04_features$(cluster).err
output = logs/04_features$(cluster).out

#set requirements
requirements = (HasCHTCStaging == true) && (HasChtcProjects == true) && (OpSysMajorVer > 7)

#make requests and queue
request_cpus = 8
request_memory = 12GB
request_disk = 12GB

queue
