#link container 
container_image = docker://quay.io/qiime2/amplicon:2025.4

#reference your sh file
executable = 06_rarefact.sh

staging_output = file:///staging/mmichaelis/input_outputs

#state path to input files from staging folder 02_dada2_qc (not 03)
transfer_input_files = \
  $(staging_output)/02_dada2_qc/table.qza, \
  $(staging_output)/04_phytree/rooted-tree.qza, \
  $(staging_output)/02_dada2_qc/sample-metadata.tsv

#state output files to be transferred
transfer_output_files = alpha-rarefaction.qzv

#state path to desired location of output files
transfer_output_remaps = "alpha-rarefaction.qzv = $(staging_output)/06_rarefact/alpha-rarefaction.qzv"

#state path/name of log, err and out files
log = logs/06_rarefact$(cluster).log
error = logs/06_rarefact$(cluster).err
output = logs/06_rarefact$(cluster).out

requirements = (HasCHTCStaging == true) && (HasChtcProjects == true)

#make requests and queue
request_cpus = 8
request_memory = 10GB
request_disk = 10GB

queue
