#link container 
container_image = docker://quay.io/qiime2/amplicon:2025.4

#reference sh script
executable = 07_taxonomy.sh
staging_path = file:///staging/mmichaelis/input_outputs

#state path to input files
transfer_input_files = \
  $(staging_path)/02_dada2_qc/rep-seqs.qza, \
  $(staging_path)/02_dada2_qc/table.qza, \
  $(staging_path)/02_dada2_qc/sample-metadata.tsv

#state the output files
transfer_output_files = taxonomy.qza, taxonomy.qzv, taxa-bar-plots.qzv

#remap outputs to desired location
transfer_output_remaps = "taxonomy.qza = $(staging_path)/07_taxonomy/taxonomy.qza; \
  taxonomy.qzv = $(staging_path)/07_taxonomy/taxonomy.qzv; \
  taxa-bar-plots.qzv = $(staging_path)/07_taxonomy/taxa-bar-plots.qzv"

#create log/err/out files
log = logs/07_taxonomy$(cluster).log
error = logs/07_taxonomy$(cluster).err
output = logs/07_taxonomy$(cluster).out

#set requirements
requirements = (HasCHTCStaging == true) && (HasChtcProjects == true) && (OpSysMajorVer > 7)

#make requests and queue
request_cpus = 8
request_memory = 12GB
request_disk = 12GB

queue
