#link container 
container_image = docker://quay.io/qiime2/amplicon:2025.4

#reference sh script
executable = 08_ancombc.sh
staging_path = file:///staging/mmichaelis/input_outputs

#state path to input files
transfer_input_files = \
  $(staging_path)/02_dada2_qc/table.qza, \
  $(staging_path)/02_dada2_qc/sample-metadata.tsv, \
  $(staging_path)/07_taxonomy/taxonomy.qza

#state the output files
transfer_output_files = gut-table.qza, ancombc-subject.qza, da-barplot-subject.qzv, \
  gut-table-l6.qza, l6-ancombc-subject.qza, l6-da-barplot-subject.qzv

#remap outputs to desired location
transfer_output_remaps = "gut-table.qza = $(staging_path)/08_ancombc/gut-table.qza; ancombc-subject.qza=$(staging_path)/08_ancombc/ancombc-subject.qza; \
  da-barplot-subject.qzv =  $(staging_path)/08_ancombc/da-barplot-subject.qzv; gut-table-l6.qza = $(staging_path)/08_ancombc/gut-table-l6.qza; \
  l6-ancombc-subject.qza = $(staging_path)/08_ancombc/l6-ancombc-subject.qza; \
  l6-da-barplot-subject.qzv = $(staging_path)/08_ancombc/l6-da-barplot-subject.qzv"
 
#create log/err/out files
log = logs/08_ancombc$(cluster).log
error = logs/08_ancombc$(cluster).err
output = logs/08_ancombc$(cluster).out

#set requirements
requirements = (HasCHTCStaging == true) && (HasChtcProjects == true) && (OpSysMajorVer > 7)

#make requests and queue
request_cpus = 8
request_memory = 12GB
request_disk = 12GB

queue
