#link container 
container_image = docker://quay.io/qiime2/amplicon:2025.4

#reference your sh file
executable = 08_ancombc.sh

staging_path = file:///staging/mmichaelis/input_outputs

#state path to input files from staging folder 02_dada2_qc (not 03)
transfer_input_files = \
  $(staging_path)/02_dada2_qc/table.qza, \
  $(staging_path)/02_dada2_qc/sample-metadata.tsv, \
  $(staging_path)/07_taxonomy/taxonomy.qza

#state output files to be transferred
transfer_output_files = gut-table.qza, ancombc-subject.qza, da-barplot-subject.qzv, \
  gut-table-l6.qza, l6-ancombc-subject.qza, l6-da-barplot-subject.qzv

#state path to desired location of output files
transfer_output_remaps = "gut-table.qza = $(staging_path)/08_ancombc/gut-table.qza; ancombc-subject.qza=$(staging_path)/08_ancombc/ancombc-subject.qza; \
  da-barplot-subject.qzv =  $(staging_path)/08_ancombc/da-barplot-subject.qzv; gut-table-l6.qza = $(staging_path)/08_ancombc/gut-table-l6.qza; \
  l6-ancombc-subject.qza = $(staging_path)/08_ancombc/l6-ancombc-subject.qza; \
  l6-da-barplot-subject.qzv = $(staging_path)/08_ancombc/l6-da-barplot-subject.qzv"
 
#state path/name of log, err and out files
log = logs/08_ancombc$(cluster).log
error = logs/08_ancombc$(cluster).err
output = logs/08_ancombc$(cluster).out

requirements = (HasCHTCStaging == true) && (HasChtcProjects == true)

#make requests and queue
request_cpus = 8
request_memory = 12GB
request_disk = 12GB

queue
