#link container 
container_image = docker://quay.io/qiime2/amplicon:2025.4

#reference sh script
executable = 08_ancombc.sh
staging_path = file:///staging/$(netid)/$(project)/input_outputs

arguments = $(column)

# VARIABLES -----------
#column=vegetation
#netid=ptran5
#project=test_project


#state path to input files
transfer_input_files = \
  $(staging_path)/02_dada2_qc/table.qza, \
  $(staging_path)/00_pipeline_inputs/sample-metadata.tsv, \
  $(staging_path)/07_taxonomy/taxonomy.qza

#state the output files
transfer_output_files = ancombc-$(column).qza, \
	table-level-6.qza, \
	da-barplot-$(column).qzv, \
	level-6-ancombc-$(column).qza, \
	level-6-da-barplot-$(column).qzv

#remap outputs to desired location
transfer_output_remaps = "ancombc-$(column).qza=$(staging_path)/08_ancombc/ancombc-$(column).qza; \
  da-barplot-$(column).qzv =  $(staging_path)/08_ancombc/da-barplot-$(column).qzv; \ 
  table-level-6.qza = $(staging_path)/08_ancombc/table-level-6.qza; \
  level-6-ancombc-$(column).qza = $(staging_path)/08_ancombc/level-6-ancombc-$(column).qza; \
  level-6-da-barplot-$(column).qzv = $(staging_path)/08_ancombc/level-6-da-barplot-$(column).qzv"
 
#create log/err/out files
log = logs/08_ancombc$(cluster).log
error = logs/08_ancombc$(cluster).err
output = logs/08_ancombc$(cluster).out

#set requirements
requirements = (HasCHTCStaging == true) && (HasChtcProjects == true) && (OpSysMajorVer > 7)

#make requests and queue
request_cpus = 8
request_memory = 12GB
request_disk = 12GB

queue
